"""Generate the per-title manifest consumed by kt_host from the user's own XBE.

The manifest holds everything title-specific (fs: patch sites, HLE symbol
addresses), so the repository itself never contains data derived from a game.

usage: gen_manifest.py <default.xbe> <symbols.txt> <out/manifest.txt>
"""
import sys

from capstone import CS_ARCH_X86, CS_MODE_32, Cs
from capstone.x86 import X86_OP_MEM, X86_OP_REG, X86_REG_FS

import os as _os, sys as _sys; _sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))  # embedded Python does not add the script directory
from xbelib import ROOT, Xbe, kernel_names, load_symbols

# Xbox KPCR fields the code reads through fs:. Windows uses these TEB offsets
# for other things (fs:[4] is StackBase), so each access is redirected to a
# per-thread fake KPCR. fs:[0] (SEH chain) is layout-compatible and left alone.
KPCR_OFFSETS = {0x04, 0x20, 0x24, 0x28, 0x58}
REGS = {"eax": 0, "ecx": 1, "edx": 2, "ebx": 3, "esp": 4, "ebp": 5, "esi": 6, "edi": 7}

# Every library symbol is listed; kt_host decides which ones it replaces
# (all of D3D8/DSOUND, and only implemented functions elsewhere).


def fs_patches(xbe):
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    md.detail = True
    out = []
    for s in xbe.sections:
        if not s.flags & 4 or s.name in (".rdata", ".data"):
            continue
        code = xbe.data[s.raw:s.raw + s.rsize]
        i = code.find(b"\x64")
        while i >= 0:
            ins = next(md.disasm(code[i:i + 15], s.va + i), None)
            if ins and ins.mnemonic in ("mov", "movzx") and len(ins.operands) == 2:
                dst, src = ins.operands
                if (dst.type == X86_OP_REG and src.type == X86_OP_MEM and src.mem.segment == X86_REG_FS
                        and src.mem.base == 0 and src.mem.index == 0 and src.mem.disp in KPCR_OFFSETS
                        and ins.reg_name(dst.reg) in REGS):
                    out.append((ins.address, ins.size, REGS[ins.reg_name(dst.reg)], src.mem.disp,
                                int(ins.mnemonic == "movzx")))
            i = code.find(b"\x64", i + 1)
    return out


def stack_bytes(xbe, va, sig):
    """Bytes of stack arguments the function pops.

    Taken from the first `ret N` in the code, since XbSymbolDatabase's
    parameter lists are sometimes approximate; falls back to the signature.
    """
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    for _ in range(4):  # follow `jmp target` thunks (IFoo_Bar -> CFoo_Bar)
        first = next(md.disasm(xbe.read(va, 16) or b"", va), None)
        if first and first.mnemonic == "jmp" and first.op_str.startswith("0x"):
            va = int(first.op_str, 16)
        else:
            break
    code = xbe.read(va, 0x800) or b""
    for ins in md.disasm(code, va):
        if ins.mnemonic == "ret":
            return int(ins.op_str, 0) if ins.op_str else 0
    params = sig[sig.index("(") + 1:sig.rindex(")")].split(",")
    return 4 * sum(1 for p in params if p.strip().startswith("psh"))


def derived_vars(xbe, syms):
    """D3D globals that inline XDK code reads directly but XbSymbolDatabase
    doesn't name, recovered from the code of the functions that write them."""
    out = []
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    md.detail = True
    by_name = {name: va for va, (lib, kind, name, _, _) in syms.items() if kind == "FUN"}
    # D3DDevice_SetIndices stores pIndexBuffer->Data into D3D__IndexData,
    # which the inline DrawIndexedVertices passes as its index pointer.
    va = by_name.get("D3DDevice_SetIndices")
    if va:
        for ins in md.disasm(xbe.read(va, 0x80) or b"", va):
            if ins.mnemonic == "mov" and len(ins.operands) == 2:
                dst, src = ins.operands
                if (dst.type == X86_OP_MEM and dst.mem.base == 0 and dst.mem.index == 0 and dst.mem.disp
                        and src.type == X86_OP_REG):
                    out.append((dst.mem.disp, "D3D8", "D3D__IndexData"))
                    break
            if ins.mnemonic == "ret":
                break
    return out


def write_kernel_names():
    """Generic table (from the CC0 nxdk .def); safe to keep in the repo."""
    names = kernel_names()
    path = ROOT / "src" / "generated" / "kernel_names.h"
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("// Generated by tools/gen_manifest.py from nxdk's xboxkrnl.exe.def (CC0).\n#pragma once\n\n")
        f.write("static const char* const kKernelNames[379] = {\n")
        for o in range(379):
            f.write(f'    "{names.get(o, "")}",\n')
        f.write("};\n")


def main():
    xbe_path, sym_path, out_path = sys.argv[1:4]
    xbe = Xbe(xbe_path)
    syms = load_symbols(sym_path)
    patches = fs_patches(xbe)
    hle = sorted((va, lib, name, conv, stack_bytes(xbe, va, sig)) for va, (lib, kind, name, conv, sig) in syms.items()
                 if kind == "FUN")
    with open(out_path, "w") as f:
        f.write("# kt_host manifest v1\n")
        for va, size, reg, off, mz in patches:
            f.write(f"fs {va:08x} {size} {reg} {off:x} {mz}\n")
        for va, lib, name, conv, nbytes in hle:
            f.write(f"hle {va:08x} {lib} {name} {conv} {nbytes}\n")
        for va, (lib, kind, name, _, _) in sorted(syms.items()):
            if kind == "VAR":
                f.write(f"var {va:08x} {lib} {name}\n")
        for va, lib, name in derived_vars(xbe, syms):
            f.write(f"var {va:08x} {lib} {name}\n")
    write_kernel_names()
    print(f"fs patches: {len(patches)}  hle symbols: {len(hle)} -> {out_path}")


if __name__ == "__main__":
    main()
